export const typo = {
  fontFamilies: {
    pretendard: 'Pretendard',
    poppins: 'Poppins',
  },
  fontWeights: {
    'pretendard-0': '700',
    'pretendard-1': '600',
    'pretendard-2': '500',
    'pretendard-3': '800',
    'poppins-4': '600',
    'poppins-5': '500',
    'poppins-6': '700',
  },
  fontSize: {
    '0': '8px',
    '1': '10px',
    '2': '12px',
    '3': '14px',
    '4': '16px',
    '5': '18px',
    '6': '20px',
    '7': '24px',
    '8': '30px',
    '9': '36px',
    '10': '40px',
  },
  letterSpacing: {
    '0': '-2%',
    '1': '-0.6px',
    '2': '-3%',
    '3': '0%',
  },
  paragraphSpacing: {
    '0': '0px',
    '1': '5px',
  },
  H1: {
    bold: {
      fontFamily: 'Pretendard',
      fontWeight: '700',
      lineHeight: '48px',
      fontSize: '40px',
      letterSpacing: '-2%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    semibold: {
      fontFamily: 'Pretendard',
      fontWeight: '600',
      lineHeight: '48px',
      fontSize: '40px',
      letterSpacing: '-2%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  H2: {
    bold: {
      fontFamily: 'Pretendard',
      fontWeight: '700',
      lineHeight: '43px',
      fontSize: '36px',
      letterSpacing: '-2%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    semibold: {
      fontFamily: 'Pretendard',
      fontWeight: '600',
      lineHeight: '43px',
      fontSize: '36px',
      letterSpacing: '-2%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  H3: {
    bold: {
      fontFamily: 'Pretendard',
      fontWeight: '700',
      lineHeight: '36px',
      fontSize: '30px',
      letterSpacing: '-2%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    semibold: {
      fontFamily: 'Pretendard',
      fontWeight: '600',
      lineHeight: '36px',
      fontSize: '30px',
      letterSpacing: '-2%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    medium: {
      fontFamily: 'Pretendard',
      fontWeight: '500',
      lineHeight: '36px',
      fontSize: '30px',
      letterSpacing: '-2%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  H4: {
    bold: {
      fontFamily: 'Pretendard',
      fontWeight: '700',
      lineHeight: '30px',
      fontSize: '24px',
      letterSpacing: '-2%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    semibold: {
      fontFamily: 'Pretendard',
      fontWeight: '600',
      lineHeight: '30px',
      fontSize: '24px',
      letterSpacing: '-2%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    medium: {
      fontFamily: 'Pretendard',
      fontWeight: '500',
      lineHeight: '30px',
      fontSize: '24px',
      letterSpacing: '-2%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  H5: {
    bold: {
      fontFamily: 'Pretendard',
      fontWeight: '700',
      lineHeight: '24px',
      fontSize: '20px',
      letterSpacing: '-2%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    semibold: {
      fontFamily: 'Pretendard',
      fontWeight: '600',
      lineHeight: '24px',
      fontSize: '20px',
      letterSpacing: '-2%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    medium: {
      fontFamily: 'Pretendard',
      fontWeight: '500',
      lineHeight: '24px',
      fontSize: '20px',
      letterSpacing: '-2%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  body1: {
    extrabold: {
      fontFamily: 'Pretendard',
      fontWeight: '800',
      lineHeight: '23px',
      fontSize: '18px',
      letterSpacing: '-2%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    bold: {
      fontFamily: 'Pretendard',
      fontWeight: '700',
      lineHeight: '23px',
      fontSize: '18px',
      letterSpacing: '-2%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    semibold: {
      fontFamily: 'Pretendard',
      fontWeight: '600',
      lineHeight: '23px',
      fontSize: '18px',
      letterSpacing: '-2%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    medium: {
      fontFamily: 'Pretendard',
      fontWeight: '500',
      lineHeight: '23px',
      fontSize: '18px',
      letterSpacing: '-0.6px',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  body2: {
    extrabold: {
      fontFamily: 'Pretendard',
      fontWeight: '800',
      lineHeight: '24px',
      fontSize: '16px',
      letterSpacing: '3%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    bold: {
      fontFamily: 'Pretendard',
      fontWeight: '700',
      lineHeight: '24px',
      fontSize: '16px',
      letterSpacing: '3%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    semibold: {
      fontFamily: 'Pretendard',
      fontWeight: '600',
      lineHeight: '24px',
      fontSize: '16px',
      letterSpacing: '3%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    medium: {
      fontFamily: 'Pretendard',
      fontWeight: '500',
      lineHeight: '24px',
      fontSize: '16px',
      letterSpacing: '3%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  body3: {
    extrabold: {
      fontFamily: 'Pretendard',
      fontWeight: '800',
      lineHeight: '18px',
      fontSize: '14px',
      letterSpacing: '3%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    semibold: {
      fontFamily: 'Pretendard',
      fontWeight: '600',
      lineHeight: '18px',
      fontSize: '14px',
      letterSpacing: '3%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    bold: {
      fontFamily: 'Pretendard',
      fontWeight: '700',
      lineHeight: '18px',
      fontSize: '14px',
      letterSpacing: '3%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    medium: {
      fontFamily: 'Pretendard',
      fontWeight: '500',
      lineHeight: '18px',
      fontSize: '14px',
      letterSpacing: '3%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  detail1: {
    bold: {
      fontFamily: 'Pretendard',
      fontWeight: '700',
      lineHeight: '16px',
      fontSize: '12px',
      letterSpacing: '3%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    semibold: {
      fontFamily: 'Pretendard',
      fontWeight: '600',
      lineHeight: '16px',
      fontSize: '12px',
      letterSpacing: '3%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    medium: {
      fontFamily: 'Pretendard',
      fontWeight: '500',
      lineHeight: '16px',
      fontSize: '12px',
      letterSpacing: '3%',
      paragraphSpacing: '1px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  detail2: {
    semibold: {
      fontFamily: 'Pretendard',
      fontWeight: '600',
      lineHeight: '12px',
      fontSize: '10px',
      letterSpacing: '3%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    bold: {
      fontFamily: 'Pretendard',
      fontWeight: '700',
      lineHeight: '12px',
      fontSize: '10px',
      letterSpacing: '1px',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  detail3: {
    bold: {
      fontFamily: 'Pretendard',
      fontWeight: '700',
      lineHeight: '10px',
      fontSize: '8px',
      letterSpacing: '3%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    semibold: {
      fontFamily: 'Pretendard',
      fontWeight: '600',
      lineHeight: '10px',
      fontSize: '8px',
      letterSpacing: '3%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    medium: {
      fontFamily: 'Pretendard',
      fontWeight: '500',
      lineHeight: '10px',
      fontSize: '8px',
      letterSpacing: '3%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  'en-H1': {
    semibold: {
      fontFamily: 'Poppins',
      fontWeight: '600',
      lineHeight: '36px',
      fontSize: '24px',
      letterSpacing: '3%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    Medium: {
      fontFamily: 'Poppins',
      fontWeight: '500',
      lineHeight: '36px',
      fontSize: '24px',
      letterSpacing: '3%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
  'en-H2': {
    bold: {
      fontFamily: 'Poppins',
      fontWeight: '700',
      lineHeight: '24px',
      fontSize: '16px',
      letterSpacing: '3%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    smeiblod: {
      fontFamily: 'Poppins',
      fontWeight: '600',
      lineHeight: '24px',
      fontSize: '16px',
      letterSpacing: '3%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
    medium: {
      fontFamily: 'Poppins',
      fontWeight: '500',
      lineHeight: '24px',
      fontSize: '16px',
      letterSpacing: '3%',
      paragraphSpacing: '0px',
      paragraphIndent: '0px',
      textCase: 'none',
      textDecoration: 'none',
    },
  },
} as const;
