import { DefaultTheme } from 'styled-components';

export const calcRatio = (innerPx: number, OuterPx: number) =>
  `${Math.floor((innerPx * 100) / OuterPx)}%`;
export const calcRem = (px: number) => `${px / 16}rem`;

const theme: DefaultTheme = {
  colors: {
    red: '#ff6b6b',
    bg: 'linear-gradient(180deg, #ffffff 0%, #dee2f1 100%)',
    grayscale: {
      white: '#ffffff',
      gray50: '#f8f9fc',
      gray100: '#e8ebf5',
      gray200: '#dcdcea',
      gray300: '#b8b8cc',
      gray400: '#9191a6',
      gray500: '#6c6c80',
      gray600: '#565666',
      gray700: '#434350',
      gray800: '#2b2b33',
      gray900: '#0b0b0d',
      black: '#000000',
    },
    glassicon: {
      blue: 'linear-gradient(85deg, #5d82fe 0%, #90a9fe 100%)',
      blue2: '#90a9fe73',
      blur2: 'linear-gradient(85deg, #ffffff 0%, #90a9fe 100%)',
      purple: 'linear-gradient(85deg, #8d70ff 0%, #b4a1ff 100%)',
      purple2: '#c7b9ff66',
    },
    primary: {
      'classcope-blue-5': '#678afe',
      'classcope-blue-4': '#7795fe',
      'classcope-blue-3': '#90a9fe',
      'classcope-blue-2': '#acbfff',
      'classcope-blue-1': '#cdd8ff',
      'classcope-blue-0.5': '#e5ebff',
    },
    secondary: {
      'classcope-purple-5': '#8d70ff',
      'classcope-purple-4': '#9980ff',
      'classcope-purple-3': '#b4a1ff',
      'classcope-purple-2': '#c7b9ff',
      'classcope-purple-1': '#ded6ff',
      'classcope-purple-0.5': '#ebe5ff',
    },
  },
  shadows: {
    search: '0px 4px 18px 0px #cdd8ff3d',
    'search-pressed': '0px 2px 15.333px 0px #acbfff73',
    card: '4px 3px 16px 0px #6c6c8005',
    'main-category-button': '0px 4.78px 21.509px 0px #cdd8ff3d',
    'main-category-button-click': '0px 3.585px 11.95px 0px #90a9fe66',
    header: '0px 1px 7px 0px #6c6c8070',
  },
  typography: {
    fontFamilies: {
      pretendard: 'Pretendard',
      poppins: 'Poppins',
    },
    lineHeights: {
      '0': 48,
      '1': 43,
      '2': 36,
      '3': 46,
      '4': 30,
      '5': 24,
      '6': 23,
      '7': '23%',
      '8': 18,
      '9': 14,
      '10': 12,
      '11': 10,
    },
    fontWeights: {
      'pretendard-0': 'Bold',
      'pretendard-1': 'SemiBold',
      'pretendard-2': 'Medium',
      'pretendard-3': 'ExtraBold',
      'poppins-4': 'SemiBold',
      'poppins-5': 'Medium',
      'poppins-6': 'Bold',
    },
    fontSizes: {
      '0': 8,
      '1': 10,
      '2': 12,
      '3': 14,
      '4': 16,
      '5': 18,
      '6': 20,
      '7': 24,
      '8': 30,
      '9': 36,
      '10': 40,
    },
    letterSpacing: {
      '0': -0.6,
      '1': '-3%',
      '2': '0%',
    },
    paragraphSpacing: {
      '0': 0,
      '1': 5,
    },
    typographyStyles: {
      H1: {
        bold: {
          fontFamily: 'Pretendard',
          fontWeight: 'Bold',
          lineHeight: '48px',
          fontSize: '40px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        semibold: {
          fontFamily: 'Pretendard',
          fontWeight: 'SemiBold',
          lineHeight: '48px',
          fontSize: '40px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
      },
      H2: {
        bold: {
          fontFamily: 'Pretendard',
          fontWeight: 'Bold',
          lineHeight: '43px',
          fontSize: '36px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        semibold: {
          fontFamily: 'Pretendard',
          fontWeight: 'SemiBold',
          lineHeight: '43px',
          fontSize: '36px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
      },
      H3: {
        bold: {
          fontFamily: 'Pretendard',
          fontWeight: 'Bold',
          lineHeight: '36px',
          fontSize: '30px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        semibold: {
          fontFamily: 'Pretendard',
          fontWeight: 'SemiBold',
          lineHeight: '46px',
          fontSize: '30px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        medium: {
          fontFamily: 'Pretendard',
          fontWeight: 'Medium',
          lineHeight: '36px',
          fontSize: '30px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
      },
      H4: {
        bold: {
          fontFamily: 'Pretendard',
          fontWeight: 'Bold',
          lineHeight: '30px',
          fontSize: '24px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        semibold: {
          fontFamily: 'Pretendard',
          fontWeight: 'SemiBold',
          lineHeight: '30px',
          fontSize: '24px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        medium: {
          fontFamily: 'Pretendard',
          fontWeight: 'Medium',
          lineHeight: '30px',
          fontSize: '24px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
      },
      H5: {
        bold: {
          fontFamily: 'Pretendard',
          fontWeight: 'Bold',
          lineHeight: '24px',
          fontSize: '20px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        semibold: {
          fontFamily: 'Pretendard',
          fontWeight: 'SemiBold',
          lineHeight: '24px',
          fontSize: '20px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        medium: {
          fontFamily: 'Pretendard',
          fontWeight: 'Medium',
          lineHeight: '24px',
          fontSize: '20px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
      },
      body1: {
        Extrabold: {
          fontFamily: 'Pretendard',
          fontWeight: 'ExtraBold',
          lineHeight: '23px',
          fontSize: '18px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        bold: {
          fontFamily: 'Pretendard',
          fontWeight: 'Bold',
          lineHeight: '23px',
          fontSize: '18px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        semibold: {
          fontFamily: 'Pretendard',
          fontWeight: 'SemiBold',
          lineHeight: '23%',
          fontSize: '18px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        medium: {
          fontFamily: 'Pretendard',
          fontWeight: 'Medium',
          lineHeight: '23px',
          fontSize: '18px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
      },
      body2: {
        extrabold: {
          fontFamily: 'Pretendard',
          fontWeight: 'ExtraBold',
          lineHeight: '24px',
          fontSize: '16px',
          letterSpacing: '-3%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        bold: {
          fontFamily: 'Pretendard',
          fontWeight: 'Bold',
          lineHeight: '24px',
          fontSize: '16px',
          letterSpacing: '-3%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        semibold: {
          fontFamily: 'Pretendard',
          fontWeight: 'SemiBold',
          lineHeight: '24px',
          fontSize: '16px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        medium: {
          fontFamily: 'Pretendard',
          fontWeight: 'Medium',
          lineHeight: '24px',
          fontSize: '16px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
      },
      body3: {
        extrabold: {
          fontFamily: 'Pretendard',
          fontWeight: 'ExtraBold',
          lineHeight: '18px',
          fontSize: '14px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        semibold: {
          fontFamily: 'Pretendard',
          fontWeight: 'SemiBold',
          lineHeight: '18px',
          fontSize: '14px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        bold: {
          fontFamily: 'Pretendard',
          fontWeight: 'Bold',
          lineHeight: '18px',
          fontSize: '14px',
          letterSpacing: '-3%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        medium: {
          fontFamily: 'Pretendard',
          fontWeight: 'Medium',
          lineHeight: '18px',
          fontSize: '14px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
      },
      detail1: {
        bold: {
          fontFamily: 'Pretendard',
          fontWeight: 'Bold',
          lineHeight: '14px',
          fontSize: '12px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        semibold: {
          fontFamily: 'Pretendard',
          fontWeight: 'SemiBold',
          lineHeight: '14px',
          fontSize: '12px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        medium: {
          fontFamily: 'Pretendard',
          fontWeight: 'Medium',
          lineHeight: '14px',
          fontSize: '12px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '5px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
      },
      detail2: {
        semibold: {
          fontFamily: 'Pretendard',
          fontWeight: 'SemiBold',
          lineHeight: '12px',
          fontSize: '10px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        bold: {
          fontFamily: 'Pretendard',
          fontWeight: 'Bold',
          lineHeight: '12px',
          fontSize: '10px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
      },
      detail3: {
        bold: {
          fontFamily: 'Pretendard',
          fontWeight: 'Bold',
          lineHeight: '10px',
          fontSize: '8px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        semibold: {
          fontFamily: 'Pretendard',
          fontWeight: 'SemiBold',
          lineHeight: '10px',
          fontSize: '8px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        medium: {
          fontFamily: 'Pretendard',
          fontWeight: 'Medium',
          lineHeight: '10px',
          fontSize: '8px',
          letterSpacing: '-0.6px',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
      },
      'en-H1': {
        semibold: {
          fontFamily: 'Poppins',
          fontWeight: 'SemiBold',
          lineHeight: '36px',
          fontSize: '24px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        Medium: {
          fontFamily: 'Poppins',
          fontWeight: 'Medium',
          lineHeight: '36px',
          fontSize: '24px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
      },
      'en-H2': {
        bold: {
          fontFamily: 'Poppins',
          fontWeight: 'Bold',
          lineHeight: '24px',
          fontSize: '16px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        smeiblod: {
          fontFamily: 'Poppins',
          fontWeight: 'SemiBold',
          lineHeight: '24px',
          fontSize: '16px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
        medium: {
          fontFamily: 'Poppins',
          fontWeight: 'Medium',
          lineHeight: '24px',
          fontSize: '16px',
          letterSpacing: '0%',
          paragraphSpacing: '0px',
          paragraphIndent: '0px',
          textCase: 'none',
          textDecoration: 'none',
        },
      },
    },
  },
};

export default theme;
